from user import *
user1 = User("Tommy", 2, 0)
user2 = User('Hellene', 1, 0)
print(user1)
print(user2)
user1.give_a_taco(user2)
print(user1)
print(user2)
user1.give_a_taco(user2)
print(user1)
print(user2)
user1.give_a_taco(user2)
print(user1)
print(user2)
